# Generated by Django 4.1.5 on 2023-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, choices=[('H', 'Hard'), ('M', 'Medium'), ('E', 'Easy')], default='E', max_length=1),
        ),
    ]
