# Generated by Django 4.1.5 on 2023-05-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_subject_availability_alter_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, choices=[('H', 'Hard'), ('E', 'Easy'), ('M', 'Medium')], default='E', max_length=1),
        ),
    ]
